### ISSUE TITLE
What is the content of the config.properties file

### ISSUE THREAD

**Issue by SanchayGupta1197** [micromata/JiraRestClient#5]

**Comment by mischah** [comment]
Hej, maybe @cschulc is still around to answer your question.

**Comment by cschulc** [comment]
You can see the properties in the clas BaseTest at bottom.

**Comment by SanchayGupta1197** [comment]
Is this library available as the maven dependency?

**Comment by cschulc** [comment]
no

**Comment by mischah** [comment]
Thanks @cschulc.
